#file: noinspection undefined
auth:
  service:
    test:  MONGODB #IN-MEMORY
spring:
  application:
    name: XLG-DGL-IDENTITY-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://api-test:api-test@cluster1.ssk95tn.mongodb.net/test-users?retryWrites=true&w=majority
  config:
    name: ${spring.application.name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false