#file: noinspection undefined
auth:
  service:
    test: IN-MEMORY #MONGODB #
spring:
  data:
    mongodb:
      uri: mongodb+srv://api-test:api-test@cluster1.ssk95tn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
